# Alacritty Config
# R: v0.1.0, E: 2024/07/30

[window]
opacity = 1
blur = true

# `Consolas 7NF` nerd font should be installed
[font]
normal = { family = "Consolas 7NF", style = "Regular" }
size = 11.25

# Colors (from `Stup0r38/iceberg-awesome`)
[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[colors.normal]
black = "#161821"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#c6c8d1"

[colors.bright]
black = "#6b7089"
red = "#e98989"
green = "#c0ca8e"
yellow = "#e9b189"
blue = "#91acd1"
magenta = "#ada0d3"
cyan = "#95c4ce"
white = "#d2d4de"
